INSERT INTO PRO_TRENER (NR_TRENERA,IMIE,NAZWISKO)
VALUES(1,'Oleg','Woodard');
INSERT INTO PRO_TRENER (NR_TRENERA,IMIE,NAZWISKO)
VALUES (2,'Tallulah','Carey');
INSERT INTO PRO_TRENER (NR_TRENERA,IMIE,NAZWISKO)
VALUES (3,'Kasimir','Sanchez');
INSERT INTO PRO_TRENER (NR_TRENERA,IMIE,NAZWISKO)
VALUES (4,'Azalia','Whitfield');
INSERT INTO PRO_TRENER (NR_TRENERA,IMIE,NAZWISKO)
VALUES (5,'Deacon','Avila');
INSERT INTO PRO_TRENER (NR_TRENERA,IMIE,NAZWISKO)
VALUES (6,'Chancellor','Perez');
INSERT INTO PRO_TRENER (NR_TRENERA,IMIE,NAZWISKO)
VALUES (7,'Plato','Logan');
